Repository netlight-johannadagfalk/goclimate, pull requests merged in 2021-09, with the labels that each got.

#72 Project 2 [feat]: Category results in footprint form view
  app/assets/main/react_components/footprint_form/CategoryPage.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/OptionList.jsx
  app/assets/main/react_components/footprint_form/OptionNumerical.jsx
  app/assets/main/react_components/footprint_form/ProgressBar.jsx
  app/assets/main/react_components/footprint_form/QuestionPage.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_form/WorldPage.jsx
  app/assets/main/react_components/footprint_form/constructObjects.js
  app/assets/main/react_components/footprint_form/footprint-data.js
  app/assets/main/react_components/footprint_result/CategoryChart.jsx
  app/assets/main/react_components/footprint_result/ResultBar.jsx
  app/assets/main/react_components/footprint_result/ResultText.jsx
  app/controllers/lifestyle_footprints_controller.rb
Labels: Project 2

#74 Project 2 [feat]: Sign up page in form view
  app/assets/main/react_components/footprint_form/CategoryPage.jsx
  app/assets/main/react_components/footprint_form/Container.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_form/WorldPage.jsx
  app/assets/main/react_components/footprint_form/footprint-data.js
  app/assets/main/react_components/footprint_result/CategoryChart.jsx
  app/assets/main/react_components/footprint_result/MembershipTypeSelector.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
  app/controllers/lifestyle_footprints_controller.rb
  app/views/lifestyle_footprints/new.html.erb
Labels: Project 2

#75 Project 2 [SPIKE]: Add a component that shows current referral code
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
Labels: Project 2

#78 Project 2 [feat]: Information section in footprint view
  app/assets/main/react_components/footprint_form/Container.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/InformationSection.jsx
  app/assets/main/react_components/footprint_result/LatestProjectsList.jsx
  app/assets/main/react_components/footprint_result/MoneyUsageList.jsx
  app/controllers/lifestyle_footprints_controller.rb
  app/views/lifestyle_footprints/new.html.erb
Labels: Project 2

#79 Project 2 [feat] SignUp container with membership select and payment
  app/assets/main/react_components/footprint_form/AnswerButton.jsx
  app/assets/main/react_components/footprint_form/Container.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/OptionNumerical.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_result/MembershipSelector.jsx
  app/assets/main/react_components/footprint_result/MembershipTypeSelector.jsx
  app/assets/main/react_components/footprint_result/Payment.jsx
  app/assets/main/react_components/footprint_result/PriceText.jsx
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
  app/assets/main/react_components/footprint_result/ResultContainer.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
  app/assets/main/react_components/footprint_result/WorldComparisonChart.jsx
  app/assets/main/react_components/footprint_result/result-helper.js
  app/views/devise/registrations/new.html.erb
  package.json
  yarn.lock
Labels: Project 2

#81 P1/feat demo images
  app/assets/main/components/category_colors.css
  app/assets/main/react_components/User/CarouselActionItem.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
  app/assets/main/react_components/User/contexts/UserActionsContext.js
  app/controllers/dashboard_controller.rb
  public/ClimatePointGlobe.png
  public/achievement_images/AchievementCar.png
  public/achievement_images/AchievementClimateFriend.png
  public/achievement_images/AchievementFlights.png
  public/achievement_images/AchievementFood.png
  public/achievement_images/AchievementHousing.png
  public/achievement_images/AchievementPublicEmissions.png
  public/achievement_images/AchievementShopping.png
  public/achievement_images/AchievementStarActive.png
  public/achievement_images/AchievementStarInactive.png
  public/action_images/Bike.png
  public/action_images/Carpool.png
  public/action_images/Eco-vacation.png
  public/action_images/Electric-car.png
  public/action_images/Food-waste.png
  public/action_images/Globe.png
  public/action_images/Protest.png
  public/action_images/SecondHand.png
  public/action_images/Shopping.png
  public/action_images/SolarPanels.png
  public/action_images/Tell-a-friend.png
  public/action_images/Vegan.png
  public/action_images/Vegetarian.png
  public/action_images/Vote-eco.png
Labels: Project 1

#80 Project 2 [feat]: Submit on enter at referral code
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
Labels: Project 2

#83 Project 2 [fix] Cleaned unused data declarations
  app/assets/main/react_components/footprint_country_select/CountryForm.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_result/MembershipSelector.jsx
Labels: Project 2

#82 Project 2 [fix] Remove irrelevant links when price is free
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_result/MembershipSelector.jsx
  app/assets/main/react_components/footprint_result/Payment.jsx
  app/assets/main/react_components/footprint_result/PriceText.jsx
Labels: Project 2

#85 P1/feat/44 style carousel cards
  app/assets/main/components/category_colors.css
  app/assets/main/react_components/User/CarouselActionItem.jsx
  app/assets/main/react_components/User/CarouselContainer.jsx
  app/assets/main/react_components/User/CarouselList.jsx
  app/assets/main/react_components/User/ClimateActionsContainer.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
  app/views/admin/climate_actions/_form.html.erb
  public/climateActionsEx/Globe.png
  public/climateActionsEx/Vegetarian.png
  tailwind.config.js
Labels: Project 1

#87 P1/feat/40 combining kanban cards
  app/assets/main/react_components/User/CarouselActionItem.jsx
  app/assets/main/react_components/User/Dashboard.jsx
  app/assets/main/react_components/User/KanbanActionColumn.jsx
  app/assets/main/react_components/User/KanbanActionContainer.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
  app/assets/main/react_components/User/contexts/UserActionsContext.js
  app/controllers/dashboard_controller.rb
  package.json
Labels: Project 1

#88 Project 2 [fix]: Pull remote
  app/assets/main/react_components/footprint_result/ResultContainer.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
  app/controllers/lifestyle_footprints_controller.rb
  app/models/business_contact.rb
  app/models/user.rb
  app/views/business/advisory/show.html.erb
  app/views/devise/registrations/_chart_world_comparison.html.erb
  app/views/devise/registrations/_sign_up_form.erb
  app/views/lifestyle_footprints/start.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_header.html.erb
  config/application.rb
  config/experiments.yml
  config/locales/activerecord.de.yml
  config/locales/activerecord.en.yml
  config/locales/activerecord.sv.yml
  config/locales/views/business/advisory.en.yml
  config/locales/views/business/advisory.eo.yml
  config/locales/views/business/advisory.sv.yml
  config/locales/views/lifestyle_footprints.en.yml
  config/locales/views/lifestyle_footprints.sv.yml
  config/locales/views/registrations.en.yml
  config/locales/views/registrations.eo.yml
  config/locales/views/registrations.sv.yml
  config/routes.rb
  spec/models/user_spec.rb
Labels: Project 2

#89 Project 2 [FEATURE]: Clicking on terms link opens new tab with info
  app/assets/main/react_components/footprint_form/Container.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
Labels: Project 2

#92 Progressbar in category colors filled dependent on aperformed subitems
  app/assets/main/react_components/User/ClimateActionsContainer.jsx
  app/assets/main/react_components/User/KanbanActionColumn.jsx
  app/assets/main/react_components/User/KanbanActionContainer.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
  app/assets/main/react_components/User/ProgressBar.jsx
  app/assets/main/react_components/User/Sidebar.jsx
Labels: Project 1

#91 actions can be dragged from accepted to perform but items in performed column does not change order
  app/assets/main/react_components/User/KanbanActionColumn.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
  app/controllers/admin/admin_controller.rb
Labels: Project 1

#93 New titles hardcoded for climate action header
  app/assets/main/react_components/User/CarouselContainer.jsx
  app/assets/main/react_components/User/CarouselHeader.jsx
Labels: Project 1

#95 P1/feat/43 kanban card styling
  app/assets/main/react_components/User/CarouselContainer.jsx
  app/assets/main/react_components/User/ClimateActionsContainer.jsx
  app/assets/main/react_components/User/KanbanActionColumn.jsx
  app/assets/main/react_components/User/KanbanActionContainer.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
Labels: Project 1

#96 added shuffle on actions that is shown in carousel
  app/assets/main/react_components/User/contexts/ClimateActionsContext.js
Labels: Project 1

#98 P1/feat/54 mobile action of the month
  app/assets/main/react_components/User/CarouselList.jsx
  app/assets/main/react_components/User/ClimateActionsContainer.jsx
  package.json
  yarn.lock
Labels: Project 1

#99 P1/bug/fixed tests
  app/assets/main/react_components/User/Sidebar.jsx
  app/mailers/subscription_mailer.rb
  app/views/shared/_bottom_landscape.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/email/_action_of_the_month.html.erb
  app/views/subscription_mailer/one_more_month_email.html.erb
  spec/requests/climate_action_categories_spec.rb
  spec/requests/climate_actions_spec.rb
  spec/requests/user_climate_actions_spec.rb
Labels: Project 1

#100 Lift expanded state up to allow for only one expanded item in each co…
  app/assets/main/react_components/User/KanbanActionColumn.jsx
  app/assets/main/react_components/User/KanbanActionContainer.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
Labels: Project 1

#102 P1/feat/48 reactify footprint
  app/assets/main/react_components/User/CategoryChart.jsx
  app/assets/main/react_components/User/ClimateActionsContainer.jsx
  app/assets/main/react_components/User/Dashboard.jsx
  app/assets/main/react_components/User/FootprintContainer.jsx
  app/assets/main/react_components/User/FootprintFooter.jsx
  app/assets/main/react_components/User/MainInfo.jsx
  app/assets/main/react_components/User/MonthlyAction.jsx
  app/assets/main/react_components/User/ResultBar.jsx
  app/assets/main/react_components/User/ResultText.jsx
  app/assets/main/react_components/User/YourFootprintText.jsx
  app/assets/main/react_components/User/result-helper.js
  app/views/dashboard/show.html.erb
Labels: Project 1

#101 P1/feat/51 achievements styling
  app/assets/main/react_components/User/KanbanActionContainer.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
Labels: Project 1

#105 P1/bug button in kanban actions
  app/assets/main/react_components/User/KanbanActionColumn.jsx
  app/assets/main/react_components/User/KanbanActionContainer.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
Labels: bug, Project 1

#104 P1/feat/48 reactify footprint routing
  app/assets/main/react_components/User/ClimateActionsContainer.jsx
  app/assets/main/react_components/User/Dashboard.jsx
  app/assets/main/react_components/User/FootprintFooter.jsx
  app/assets/main/react_components/User/MainInfo.jsx
  app/views/dashboard/show.html.erb
Labels: Project 1

#103 P1/feat/49 center content relative sidebar
  app/assets/main/components/section_padding.css
  app/assets/main/react_components/User/CarouselContainer.jsx
  app/assets/main/react_components/User/ClimateActionsContainer.jsx
  app/assets/main/react_components/User/KanbanActionColumn.jsx
  app/assets/main/react_components/User/KanbanActionItem.jsx
  app/assets/main/react_components/User/MainInfo.jsx
  app/assets/main/react_components/User/MonthlyAction.jsx
  app/assets/main/react_components/User/Sidebar.jsx
  app/assets/main/react_components/User/YourFootprintText.jsx
  app/views/dashboard/show.html.erb
  package.json
  yarn.lock
Labels: Project 1

#106 P1/feat/53 mobile view carousel
  app/assets/main/react_components/User/CarouselActionItem.jsx
  app/assets/main/react_components/User/CarouselCategoryButton.jsx
  app/assets/main/react_components/User/CarouselContainer.jsx
  app/assets/main/react_components/User/CarouselList.jsx
  app/assets/main/react_components/User/ClimateActionsContainer.jsx
  package.json
  yarn.lock
Labels: Project 1

#110 P1/refactor/73 structure folders
  app/assets/main/react_components/User/Card.jsx
  app/assets/main/react_components/User/Sidebar.jsx
  app/assets/main/react_components/common/Button.jsx
  app/assets/main/react_components/common/MonthlyAction.jsx
  app/assets/main/react_components/contexts/CategoryContext.js
  app/assets/main/react_components/contexts/ClimateActionsContext.js
  app/assets/main/react_components/contexts/DeletedActionContext.js
  app/assets/main/react_components/contexts/UserActionsContext.js
  app/assets/main/react_components/dashboard/Dashboard.jsx
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselHeader.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/ProgressBar.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/sidebar/Sidebar.jsx
  app/assets/main/react_components/dashboard/footprint/CategoryChart.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintContainer.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintFooter.jsx
  app/assets/main/react_components/dashboard/footprint/MainInfo.jsx
  app/assets/main/react_components/dashboard/footprint/ResultBar.jsx
  app/assets/main/react_components/dashboard/footprint/ResultText.jsx
  app/assets/main/react_components/dashboard/footprint/YourFootprintText.jsx
  app/assets/main/react_components/helpers/result-helper.js
Labels: Project 1

#90 Project 2 [feat]: A/B testing for React vs Rails enabled
  app/controllers/lifestyle_footprints_controller.rb
  app/views/home/show.html.erb
  app/views/lifestyle_footprints/index.html.erb
  app/views/lifestyle_footprints/new.html.erb
  config/experiments.yml
Labels: Project 2

#97 Project 2 [feat]: useContext for static data
  app/assets/main/react_components/context/Footprint/LocaleContext.js
  app/assets/main/react_components/context/Footprint/ProjectsContext.js
  app/assets/main/react_components/context/Footprint/StaticDataProvider.js
  app/assets/main/react_components/context/Footprint/TextsContext.js
  app/assets/main/react_components/footprint_form/CategoryPage.jsx
  app/assets/main/react_components/footprint_form/Container.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/InformationSection.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_form/WorldPage.jsx
  app/assets/main/react_components/footprint_form/constructObjects.js
  app/assets/main/react_components/footprint_result/CategoryChart.jsx
  app/assets/main/react_components/footprint_result/FAQ.jsx
  app/assets/main/react_components/footprint_result/LatestProjectsList.jsx
  app/assets/main/react_components/footprint_result/MembershipSelector.jsx
  app/assets/main/react_components/footprint_result/MembershipTypeSelector.jsx
  app/assets/main/react_components/footprint_result/MoneyUsageList.jsx
  app/assets/main/react_components/footprint_result/Payment.jsx
  app/assets/main/react_components/footprint_result/PriceText.jsx
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
  app/assets/main/react_components/footprint_result/ResultContainer.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
  app/assets/main/react_components/footprint_result/SignUpMotivationText.jsx
  app/assets/main/react_components/footprint_result/WorldComparisonChart.jsx
  app/assets/main/react_components/footprint_result/YourFootprintText.jsx
  app/views/devise/registrations/new.html.erb
Labels: Project 2

#112 P1/feat/57 new arrow style carousel
  app/assets/main/react_components/contexts/FootprintContext.js
  app/assets/main/react_components/dashboard/Dashboard.jsx
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/footprint/CategoryChart.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintContainer.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintFooter.jsx
  app/assets/main/react_components/dashboard/footprint/MainInfo.jsx
  app/assets/main/react_components/dashboard/footprint/ResultText.jsx
  app/assets/main/react_components/dashboard/footprint/YourFootprintText.jsx
  app/views/dashboard/show.html.erb
Labels: Project 1

#115 P1/refactor/66 add screen size constants
  app/assets/main/react_components/constants/index.js
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageActions.jsx
Labels: Project 1

#114 P1/feat/63 expand items one at the time
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
Labels: Project 1

#119 p1/72-added mounting checks when callback from db is used
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
Labels: Project 1

#107 Project 2 [fix]: Apply linter and formatter
  .eslintrc.json
  app/assets/main/react_components/Button.jsx
  app/assets/main/react_components/Link.jsx
  app/assets/main/react_components/context/Footprint/LocaleContext.js
  app/assets/main/react_components/context/Footprint/ProjectsContext.js
  app/assets/main/react_components/context/Footprint/StaticDataProvider.js
  app/assets/main/react_components/context/Footprint/TextsContext.js
  app/assets/main/react_components/footprint_country_select/CountryForm.jsx
  app/assets/main/react_components/footprint_country_select/CountrySelectContainer.jsx
  app/assets/main/react_components/footprint_form/AnswerButton.jsx
  app/assets/main/react_components/footprint_form/CategoryPage.jsx
  app/assets/main/react_components/footprint_form/Container.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/InformationSection.jsx
  app/assets/main/react_components/footprint_form/OptionList.jsx
  app/assets/main/react_components/footprint_form/OptionNumerical.jsx
  app/assets/main/react_components/footprint_form/ProgressBar.jsx
  app/assets/main/react_components/footprint_form/QuestionPage.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_form/Title.jsx
  app/assets/main/react_components/footprint_form/WorldPage.jsx
  app/assets/main/react_components/footprint_form/constructObjects.js
  app/assets/main/react_components/footprint_form/footprint-data.js
  app/assets/main/react_components/footprint_result/CategoryChart.jsx
  app/assets/main/react_components/footprint_result/FAQ.jsx
  app/assets/main/react_components/footprint_result/FAQListChild.jsx
  app/assets/main/react_components/footprint_result/LatestProjectsList.jsx
  app/assets/main/react_components/footprint_result/MembershipSelector.jsx
  app/assets/main/react_components/footprint_result/MembershipTypeSelector.jsx
  app/assets/main/react_components/footprint_result/MoneyUsageList.jsx
  app/assets/main/react_components/footprint_result/Payment.jsx
  app/assets/main/react_components/footprint_result/PriceText.jsx
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
  app/assets/main/react_components/footprint_result/ResultBar.jsx
  app/assets/main/react_components/footprint_result/ResultContainer.jsx
  app/assets/main/react_components/footprint_result/ResultText.jsx
  app/assets/main/react_components/footprint_result/ResultTitle.jsx
  app/assets/main/react_components/footprint_result/SelectButton.jsx
  app/assets/main/react_components/footprint_result/SelectorMultipleTimes.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
  app/assets/main/react_components/footprint_result/SignUpMotivationText.jsx
  app/assets/main/react_components/footprint_result/SignUpTitle.jsx
  app/assets/main/react_components/footprint_result/WorldComparisonChart.jsx
  app/assets/main/react_components/footprint_result/YourFootprintText.jsx
  app/assets/main/react_components/footprint_result/result-helper.js
  package.json
  yarn.lock
Labels: Project 2

#117 changed style on imported components to avoid using important in tail…
  app/assets/main/index.css
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
  app/views/dashboard/show.html.erb
  tailwind.config.js
Labels: Project 1

#111 Project 2 [feat]: Payment in footprint view
  app/assets/main/react_components/context/Footprint/LocaleContext.js
  app/assets/main/react_components/context/Footprint/StaticDataProvider.js
  app/assets/main/react_components/footprint_form/Container.jsx
  app/assets/main/react_components/footprint_form/FootprintFormContainer.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_result/ConfirmSignUpContainer.jsx
  app/assets/main/react_components/footprint_result/Payment.jsx
  app/assets/main/react_components/footprint_result/PriceText.jsx
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
  app/views/lifestyle_footprints/new.html.erb
Labels: Project 2

#113 Project 2 [feat] Styling changes
  app/assets/main/react_components/footprint_form/CategoryPage.jsx
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_form/Title.jsx
  app/assets/main/react_components/footprint_form/WorldPage.jsx
  app/assets/main/react_components/footprint_result/CategoryChart.jsx
  app/assets/main/react_components/footprint_result/ConfirmSignUpContainer.jsx
  app/assets/main/react_components/footprint_result/Payment.jsx
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
  app/assets/main/react_components/footprint_result/SelectButton.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
  app/assets/main/react_components/footprint_result/SignUpMotivationText.jsx
  app/assets/main/react_components/footprint_result/SignUpPreamble.jsx
  tailwind.config.js
Labels: Project 2

#118 Project 2 [fix] Borders added to membership-boxes
  app/assets/main/react_components/footprint_result/SelectButton.jsx
  app/assets/main/react_components/footprint_result/SelectorMultipleTimes.jsx
Labels: Project 2

#130 P1/feat/56 mobile adapted kanban
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/MobileKanbanContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/ProgressBar.jsx
  app/views/shared/_header.html.erb
  tailwind.config.js
Labels: Project 1

#116 Project 2 [Feature]: Styling on result where footprint and offset is shown in a string
  app/assets/main/react_components/context/Footprint/StaticDataProvider.js
  app/assets/main/react_components/context/Footprint/TextsContext.js
  app/assets/main/react_components/footprint_form/Container.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_form/WorldPage.jsx
  app/assets/main/react_components/footprint_result/YourFootprintText.jsx
  app/views/lifestyle_footprints/new.html.erb
  config/locales/react/react.de.yml
  config/locales/react/react.en.yml
  config/locales/react/react.sv.yml
Labels: Project 2

#120 Project 2 [FEAT]: Wider button
  app/assets/main/react_components/footprint_form/ResultPage.jsx
Labels: Project 2

#122 Project 2 [fix] Membership text
  app/assets/main/react_components/context/Footprint/StaticDataProvider.js
  app/assets/main/react_components/context/Footprint/TextsContext.js
  app/assets/main/react_components/footprint_form/WorldPage.jsx
  app/assets/main/react_components/footprint_result/MembershipTypeSelector.jsx
  app/assets/main/react_components/footprint_result/SelectButton.jsx
  app/assets/main/react_components/footprint_result/YourFootprintText.jsx
  config/locales/react/react.de.yml
  config/locales/react/react.en.yml
  config/locales/react/react.sv.yml
Labels: Project 2

#126 Project 2 [Feat]: Result/category bars order change
  app/assets/main/react_components/footprint_result/result-helper.js
Labels: Project 2

#127 Project 2 [fix] Category page title and preamble
  app/assets/main/react_components/footprint_form/CategoryPage.jsx
  config/locales/react/react.de.yml
  config/locales/react/react.en.yml
  config/locales/react/react.sv.yml
Labels: Project 2

#128 Project 2 [FIX]: Referral input smaller
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
Labels: Project 2

#129 Project 2 [fix]: Responsive progress bar
  app/assets/main/react_components/footprint_form/ProgressBar.jsx
  app/assets/main/react_components/footprint_result/result-helper.js
  tailwind.config.js
Labels: Project 2

#133 Fixed bug: Removed z-value for bottom landscape (tree images) so whole language menu is visible
  app/views/shared/_bottom_landscape.html.erb
Labels: Project 1

#125 p1/feat/66 Replaced hard coded texts with language files using Context
  app/assets/main/react_components/common/MonthlyAction.jsx
  app/assets/main/react_components/contexts/TextContext.js
  app/assets/main/react_components/contexts/UserActionsContext.js
  app/assets/main/react_components/dashboard/Dashboard.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselHeader.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintFooter.jsx
  app/assets/main/react_components/translations/climate_actions.de.yml
  app/assets/main/react_components/translations/climate_actions.en.yml
  app/assets/main/react_components/translations/climate_actions.sv.yml
  app/views/dashboard/show.html.erb
Labels: Project 1

#131 P1/feat/26
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
  app/controllers/dashboard_controller.rb
Labels: Project 1

#138 Project 2 [bug] Referral code granted bug
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
Labels: Project 2

#139 fixed bugs
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/MobileKanbanContainer.jsx
Labels: Project 1

#140 Project 2 [bug] referral code: bug and link text gone
  app/assets/main/react_components/footprint_result/PriceText.jsx
  app/assets/main/react_components/footprint_result/ReferralCode.jsx
Labels: Project 2

#134 P1/fix overall styling
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
Labels: Project 1

#132 Project 2 [feat]: Version control for React versions
  app/assets/main/react_components/context/Footprint/StaticDataProvider.js
  app/assets/main/react_components/context/Footprint/VersionContext.js
  app/assets/main/react_components/footprint_form/Container.jsx
  app/controllers/lifestyle_footprints_controller.rb
  app/views/lifestyle_footprints/new.html.erb
  config/experiments.yml
Labels: Project 2

#135 Project 2 [feat]: Placeholders for new layout on sign up page
  app/assets/main/react_components/footprint_form/ArgumentsList.jsx
  app/assets/main/react_components/footprint_form/FormInformationSection.jsx
  app/assets/main/react_components/footprint_form/InformationSection.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_result/LatestProjectsList.jsx
  app/assets/main/react_components/footprint_result/PriceText.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
Labels: Project 2

#137 P1/feat/59 newly added kanban items at the top
  app/assets/main/react_components/contexts/UserActionsContext.js
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
Labels: Project 1

#145 P1/fix/show no circle when zero actions accepted in mobile
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/MobileKanbanContainer.jsx
Labels: Project 1

#144 P1/feat/71 sidebar styling
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/ProgressBar.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/sidebar/Sidebar.jsx
  app/views/dashboard/show.html.erb
Labels: Project 1

#136 Project 2 [feat]: Continue without membership button
  app/assets/main/react_components/Link.jsx
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  config/locales/react/react.de.yml
  config/locales/react/react.en.yml
  config/locales/react/react.sv.yml
Labels: Project 2

#141 Project 2 [fix] Pull remote
  Gemfile
  Guardfile
  app/controllers/admin/users_controller.rb
  app/controllers/flight_footprints_controller.rb
  app/controllers/flight_offsets_controller.rb
  app/controllers/user_flight_offsets_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/flight_offset.rb
  app/models/greenhouse_gases.rb
  app/models/user.rb
  app/views/admin/shared/_content_header.html.erb
  app/views/admin/users/edit.html.erb
  app/views/admin/users/index.html.erb
  app/views/admin/users/show.html.erb
  app/views/devise/registrations/_chart_world_comparison.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new_campaign.html.erb
  app/views/devise/shared/_error_messages_old.html.erb
  app/views/flight_offsets/new.html.erb
  app/views/home/show.html.erb
  app/views/projects/index.html.erb
  app/views/shared/_header.html.erb
  app/views/user_flight_offsets/index.html.erb
  app/views/users/subscriptions/show.html.erb
  config/experiments.yml
  config/locales/devise.views.en.yml
  config/locales/devise.views.sv.yml
  config/locales/models.de.yml
  config/locales/models.en.yml
  config/locales/models.eo.yml
  config/locales/models.sv.yml
  config/locales/views/business/home.en.yml
  config/locales/views/shared.en.yml
  config/locales/views/shared.sv.yml
  config/routes.rb
  db/migrate/20210908095510_add_user_id_to_flight_offset.rb
  db/schema.rb
  lib/tasks/update_user_id_in_flight_offset.rake
  spec/models/flight_offset_spec.rb
  spec/models/greenhouse_gases_spec.rb
  spec/models/user_spec.rb
Labels: Project 2

#142 Project 2 [fix]: Footprint form now redirects to user page if logged in
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/controllers/lifestyle_footprints_controller.rb
  config/locales/react/react.de.yml
  config/locales/react/react.en.yml
  config/locales/react/react.sv.yml
Labels: Project 2

#143 Project 2 [feat] Award in progress bar
  app/assets/main/react_components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/footprint_form/ProgressBar.jsx
  app/assets/main/react_components/footprint_form/footprint-data.js
  tailwind.config.js
Labels: Project 2

#147 P1/fix/kanban width and progress bar position
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
Labels: Project 1

#148 P1/feat/60 badges based on membership
  app/assets/main/components/category_colors.css
  app/assets/main/react_components/contexts/UserActionsContext.js
  app/assets/main/react_components/dashboard/Dashboard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/ProgressBar.jsx
  app/controllers/dashboard_controller.rb
  app/views/dashboard/show.html.erb
  tailwind.config.js
Labels: Project 1

#150 Project 2 [feat] Membership boxes
  app/assets/main/react_components/footprint_form/ResultPage.jsx
  app/assets/main/react_components/footprint_result/MembershipAlternative.jsx
  app/assets/main/react_components/footprint_result/MembershipSelector.jsx
  app/assets/main/react_components/footprint_result/MembershipTypeSelector.jsx
  app/assets/main/react_components/footprint_result/MembershipTypeSelectorV2.jsx
  app/assets/main/react_components/footprint_result/PriceText.jsx
  app/assets/main/react_components/footprint_result/PriceTextV2.jsx
  app/assets/main/react_components/footprint_result/SelectorMultipleTimes.jsx
  app/assets/main/react_components/footprint_result/SignUpContainer.jsx
  config/locales/react/react.de.yml
  config/locales/react/react.en.yml
  config/locales/react/react.sv.yml
Labels: Project 2

#154 Project 2 [fix] Continue to payment not to be show on free
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/SignUpPage.jsx
Labels: Project 2

#155 Project 2 [fix] Correct the flag for Country selection
  app/views/home/show.html.erb
  app/views/lifestyle_footprints/new.html.erb
Labels: Project 2

#161 Conditional rendering for empty carousel and filterbuttons
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
Labels: Project 1

#159 P1/feat/64 add toplist in carousel
  app/assets/main/react_components/dashboard/Dashboard.jsx
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
  app/controllers/dashboard_controller.rb
  app/views/dashboard/show.html.erb
Labels: Project 1

#156 Project 2 [FIX]: Project list responsiveness height adaptation fixed
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/latest_projects_list/LatestProjectsList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/latest_projects_list/components/ProjectSummary.jsx
Labels: Project 2

#158 Project 4 [FIX]: Remove border money usage list
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/form_information_section/FormInformationSection.jsx
Labels: Project 2

#163 Project 2 [feat]: Membership page preamble
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/MembershipPage.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
Labels: Project 2

#157 Project 2 [feat]: Arguments list component
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/form_information_section/FormInformationSection.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/form_information_section/components/ArgumentsList.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
Labels: Project 2

#162 Project 2 [feat]: Don't use Badge in Progress Bar if logged in
  app/assets/main/react_components/routes/lifestyle_footprints/Container.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/contexts/LocaleContext.js
  app/assets/main/react_components/routes/lifestyle_footprints/contexts/SessionContext.js
  app/assets/main/react_components/routes/lifestyle_footprints/contexts/StaticDataProvider.js
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/FootprintForm.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/ProgressBar.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/world_section/components/YourFootprintText.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/world_section/components/world_comparison_chart/WorldComparisonChart.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/SignUpPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/MembershipAlternativeV2.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/registration_page/RegistrationPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/registration_page/components/Payment.jsx
  app/views/lifestyle_footprints/new.html.erb
Labels: Project 2

#165 Project 2 [fix]: Rubocop changes and pull remote
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/admin/business_calculators_controller.rb
  app/controllers/admin/data_requests_controller.rb
  app/controllers/lifestyle_footprints_controller.rb
  app/controllers/reported_datas_controller.rb
  app/helpers/business_calculators_helper.rb
  app/models/business_calculators/calculator.rb
  app/models/business_calculators/calculator_category.rb
  app/models/business_calculators/calculator_field.rb
  app/models/climate_reports/report_area.rb
  app/views/admin/business_calculators/_form.html.erb
  app/views/admin/business_calculators/show.html.erb
  config/routes.rb
  report.20210817.150352.67299.0.001.json
  spec/factories/business_calculator_category.rb
  spec/factories/data_reporters.rb
  spec/factories/data_requests.rb
  spec/factories/newsletter_subscriber.rb
  spec/features/subscription_receipts_spec.rb
  spec/mailers/previews/data_request_mailer_preview.rb
  spec/models/business_calculators/calculator_category_spec.rb
  spec/models/business_calculators/calculator_field_spec.rb
  spec/models/business_calculators/unit_spec.rb
  spec/models/climate_reports/report_area_spec.rb
  spec/models/climate_reports/report_spec.rb
  spec/models/data_reporter_spec.rb
  spec/models/data_request_spec.rb
  spec/models/flight_offset_spec.rb
  spec/models/organization_spec.rb
  spec/models/reported_data_spec.rb
Labels: Project 2

#160 Project 2 [feat]: Arguments list responsive
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/latest_projects_list/LatestProjectsList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/form_information_section/components/ArgumentsList.jsx
  tailwind.config.js
Labels: Project 2

#166 Project 2 [feat]: Selecting value in multi-membership dropdown now selects membership itself
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/MembershipAlternativeV2.jsx
Labels: Project 2

#168 Project 2 [feat]: Green dots for current question and passed questions
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/ProgressBar.jsx
Labels: Project 2

#169 Project 2 [feat]: Added preamble component with corresponding text for public emissions
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/category_section/CategoryPage.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
Labels: Project 2

#170 Project 2 [fix]: Update text and route for leaving footprint page button
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/SignUpPage.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
Labels: Project 2

#167 P1/bug/maintain info dashboard
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/controllers/dashboard_controller.rb
Labels: Project 1

#172 Project 2 [BUG]: Added toggler that checks if granted code exists
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/ReferralCode.jsx
Labels: Project 2

#173 P1/feat/88 handle mobile dropdown
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/DropDownKanbanContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/MobileKanbanContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/views/layouts/application.html.erb
Labels: Project 1

#181 P1/feat/rubocop version
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/admin/admin_controller.rb
  app/controllers/admin/business_calculators_controller.rb
  app/controllers/admin/climate_action_categories_controller.rb
  app/controllers/admin/climate_actions_controller.rb
  app/controllers/admin/data_requests_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/reported_datas_controller.rb
  app/controllers/user_climate_actions_controller.rb
  app/helpers/business_calculators_helper.rb
  app/helpers/climate_action_categories_helper.rb
  app/helpers/climate_actions_helper.rb
  app/helpers/user_climate_actions_helper.rb
  app/mailers/subscription_mailer.rb
  app/models/business_calculators/calculator.rb
  app/models/business_calculators/calculator_category.rb
  app/models/business_calculators/calculator_field.rb
  app/models/climate_action.rb
  app/models/climate_action_category.rb
  app/models/climate_reports/report_area.rb
  app/models/user_climate_action.rb
  app/views/admin/business_calculators/_form.html.erb
  app/views/admin/business_calculators/show.html.erb
  app/views/admin/climate_action_categories/_climate_action_category.json.jbuilder
  app/views/admin/climate_action_categories/index.json.jbuilder
  app/views/admin/climate_action_categories/show.json.jbuilder
  app/views/admin/climate_actions/_climate_action.json.jbuilder
  app/views/admin/climate_actions/index.json.jbuilder
  app/views/admin/climate_actions/show.json.jbuilder
  app/views/dashboard/show.html.erb
  app/views/user_climate_actions/_user_climate_action.json.jbuilder
  app/views/user_climate_actions/index.json.jbuilder
  app/views/user_climate_actions/show.json.jbuilder
  config/routes.rb
  report.20210817.150352.67299.0.001.json
  spec/factories/business_calculator_category.rb
  spec/factories/climate_action_categories.rb
  spec/factories/climate_actions.rb
  spec/factories/data_reporters.rb
  spec/factories/data_requests.rb
  spec/factories/newsletter_subscriber.rb
  spec/factories/user_climate_actions.rb
  spec/features/subscription_receipts_spec.rb
  spec/mailers/previews/data_request_mailer_preview.rb
  spec/models/business_calculators/calculator_category_spec.rb
  spec/models/business_calculators/calculator_field_spec.rb
  spec/models/business_calculators/unit_spec.rb
  spec/models/climate_action_category_spec.rb
  spec/models/climate_action_spec.rb
  spec/models/climate_reports/report_area_spec.rb
  spec/models/climate_reports/report_spec.rb
  spec/models/data_reporter_spec.rb
  spec/models/data_request_spec.rb
  spec/models/flight_offset_spec.rb
  spec/models/organization_spec.rb
  spec/models/reported_data_spec.rb
  spec/models/user_climate_action_spec.rb
Labels: Project 1

#171 Project 2 [feat] Responsive membership boxes
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/common/PriceTextV2.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/MembershipPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/MembershipsListV2.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/MembershipAlternativeV2.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipAlternativeV2Desktop.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipAlternativeV2Mobile.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
  app/assets/shared/components/react_responsive.css
  app/assets/shared/index.css
Labels: Project 2

#176 P1/feat/65 monthly action banner
  app/assets/main/react_components/common/MonthlyAction.jsx
  app/assets/main/react_components/common/TextBanner.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
Labels: Project 1

#175 P1/refactor/90 user context
  app/assets/main/react_components/contexts/UserActionsContext.js
  app/assets/main/react_components/contexts/UserContext.js
  app/assets/main/react_components/dashboard/Dashboard.jsx
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
  app/assets/main/react_components/helpers/AchievementsHelper.js
  app/assets/main/react_components/helpers/UserActionsHelper.js
Labels: Project 1

#180 P1/feat/82 lift help functions out
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/footprint/CategoryChart.jsx
  app/assets/main/react_components/helpers/DBRequests.js
  app/assets/main/react_components/helpers/ResultHelper.js
Labels: Project 1

#186 P1/refactor/97 context files
  app/assets/main/react_components/contexts/CategoryContext.js
  app/assets/main/react_components/contexts/ClimateActionsContext.js
  app/assets/main/react_components/contexts/DeletedActionContext.js
  app/assets/main/react_components/contexts/FootprintContext.js
  app/assets/main/react_components/contexts/TextContext.js
  app/assets/main/react_components/dashboard/footprint/CategoryChart.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintContainer.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintFooter.jsx
  app/assets/main/react_components/dashboard/footprint/ResultText.jsx
Labels: Project 1

#177 Project 2 [fix]: Registration page preamble
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/registration_page/RegistrationPage.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
Labels: Project 2

#179 Project 1 - Tickets 84, 91 & 92 - Refactoring of KanbanActionItem, shadow on achievements and change button styles for user actions
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselHeader.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/KanbanCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/KanbanCardImage.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/ProgressBar.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/sidebar/Sidebar.jsx
  app/assets/main/react_components/translations/climate_actions.de.yml
  app/assets/main/react_components/translations/climate_actions.en.yml
  app/assets/main/react_components/translations/climate_actions.sv.yml
  public/achievement_images/AchievementCar.png
  public/achievement_images/AchievementClimateFriend.png
  public/achievement_images/AchievementClimateFriendShadow.png
  public/achievement_images/AchievementFlights.png
  public/achievement_images/AchievementFood.png
  public/achievement_images/AchievementHousing.png
  public/achievement_images/AchievementPublicEmissions.png
  public/achievement_images/AchievementShopping.png
Labels: Project 1

#189 Prevent click and swiping for button
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
Labels: Project 1

#190 p1/restored climate friend achievement
  app/assets/main/react_components/contexts/UserContext.js
  app/assets/main/react_components/helpers/AchievementsHelper.js
Labels: Project 1

#174 Project 2 [fix]: Small result page copy updates
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/world_section/components/YourFootprintText.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
Labels: Project 2

#191 p1/changed color on dnd marker
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
Labels: Project 1

#192 p1/restored fix width on sidebar
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
Labels: Project 1

#183 P1/feat/96 refactor css carousel action item
  app/assets/main/react_components/common/MonthlyAction.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselActionItem.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/AcceptanceStatistics.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/CategoryColorBanner.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/ImpactPoints.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/NumberOfAccepted.jsx
Labels: Project 1

#196 Flex breakpoint fix
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/MembershipsListV2.jsx
Labels: Project 2

#194 P1/feat/79 fun empty sidebar
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  public/Mascot.png
Labels: Project 1

#197 P1/collapsed sidebar scroll
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
Labels: Project 1

#198 Project 2 [FIX]: Move files
  app/assets/images/shapes/blob_5.svg
  app/assets/images/shapes/blob_6.svg
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/MoneyUsageList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/category_section/CategoryPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/world_section/components/YourFootprintText.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/SignUpPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/form_information_section/components/ArgumentsList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/MembershipPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/MembershipsList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipAlternativeV2Desktop.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipAlternativeV2Mobile.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/registration_page/RegistrationPage.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
  app/assets/shared/components/sign_up_responsive.css
  app/assets/shared/index.css
  app/views/lifestyle_footprints/new.html.erb
  config/locales/sign_up/react.de.yml
  config/locales/sign_up/react.en.yml
  config/locales/sign_up/react.sv.yml
Labels: Project 2

#203 Project 2 [fix] FAQ bottom margin
  app/assets/images/shapes/blob_5.svg
  app/assets/images/shapes/blob_6.svg
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/MoneyUsageList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/category_section/CategoryPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/world_section/components/YourFootprintText.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/SignUpPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/form_information_section/components/ArgumentsList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/MembershipPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/MembershipsList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipAlternativeV2Desktop.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipAlternativeV2Mobile.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/registration_page/RegistrationPage.jsx
  app/assets/main/react_components/translations/react.de.yml
  app/assets/main/react_components/translations/react.en.yml
  app/assets/main/react_components/translations/react.sv.yml
  app/assets/shared/components/sign_up_responsive.css
  app/assets/shared/index.css
  app/views/lifestyle_footprints/new.html.erb
  config/locales/sign_up/react.de.yml
  config/locales/sign_up/react.en.yml
  config/locales/sign_up/react.sv.yml
Labels: Project 2

#202 P1/feat/98 refactor css
  app/assets/main/react_components/common/MonthlyAction.jsx
  app/assets/main/react_components/contexts/CategoryContext.js
  app/assets/main/react_components/contexts/ClimateActionsContext.js
  app/assets/main/react_components/contexts/FootprintContext.js
  app/assets/main/react_components/dashboard/Dashboard.jsx
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselHeader.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/AcceptanceStatistics.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/CategoryColorBanner.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/ImpactPoints.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/DropDownKanbanContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/KanbanCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCardExpanded.jsx
  app/assets/main/react_components/helpers/AchievementsHelper.js
  app/assets/main/react_components/helpers/CategoryColorHelper.js
  app/assets/main/react_components/helpers/DBRequests.js
  app/assets/main/react_components/helpers/KanbanHelper.js
Labels: Project 1

#188 Project 2 [Fix]: Projects adapt short text
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/latest_projects_list/components/ProjectSummary.jsx
  app/assets/shared/components/projects.css
Labels: Project 2

#199 P1/remove comments
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/KanbanCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCardExpanded.jsx
  app/assets/main/react_components/helpers/AchievementsHelper.js
  app/assets/main/react_components/helpers/KanbanHelper.js
Labels: Project 1

#204 P1/fix/rename badge to achievement
  app/assets/main/react_components/contexts/UserContext.js
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/ProgressBar.jsx
  app/assets/main/react_components/helpers/AchievementsHelper.js
  app/assets/main/react_components/translations/climate_actions.de.yml
  app/assets/main/react_components/translations/climate_actions.en.yml
  app/assets/main/react_components/translations/climate_actions.sv.yml
  app/controllers/admin/climate_actions_controller.rb
  app/controllers/dashboard_controller.rb
  app/views/admin/climate_action_categories/_form.html.erb
  app/views/admin/climate_action_categories/index.html.erb
  app/views/admin/climate_action_categories/show.html.erb
  app/views/admin/climate_actions/_action_of_the_month.html.erb
  app/views/admin/climate_actions/_show_action_toplist.html.erb
  app/views/dashboard/show.html.erb
Labels: Project 1

#206 P1/junk/trying out refactoring
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/DropDownKanbanContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/ProgressBar.jsx
  app/controllers/admin/admin_controller.rb
Labels: Project 1

#207 Moved hardcoded text into translation files and moved drag-your-finis…
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/AcceptanceStatistics.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/translations/climate_actions.de.yml
  app/assets/main/react_components/translations/climate_actions.en.yml
  app/assets/main/react_components/translations/climate_actions.sv.yml
Labels: Project 1

#208 p1/fix bug type error when accepting/deleting actions with btn in kanban
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/helpers/DBRequests.js
Labels: Project 1

#209 P1/bug/carousel button on filtering
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
Labels: Project 1

#184 P1/bug/filter and delete user action in kanban
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
Labels: Project 1

#205 P1/feat/75 animations
  app/assets/main/react_components/contexts/UserContext.js
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/DropDownKanbanContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanActionContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/KanbanCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/ProgressBar.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/sidebar/Sidebar.jsx
  app/assets/main/react_components/helpers/UserActionsHelper.js
  app/assets/shared/components/display.css
  app/assets/shared/index.css
  package.json
  yarn.lock
Labels: Project 1

#210 P1/fix/99 change component names
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageUserActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanContainer.jsx
Labels: Project 1

#200 Project 2 [feat/fix] Styling changes and scrolltotop
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/MoneyUsageList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/ResultPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/SignUpPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/information_section/components/faq/FAQ.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/helpers/scroll-to-top.js
Labels: Project 2

#201 Project 2 [fix] Isolate versions
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/MoneyUsageList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/latest_projects_list/LatestProjectsListV1.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/latest_projects_list/LatestProjectsListV2.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/category_section/CategoryPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/form_information_section/FormInformationSection.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/MembershipPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/registration_page/RegistrationPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/information_section/InformationSection.jsx
Labels: Project 2

#213 P1/feat/add action of the month mail styling
  app/mailers/subscription_mailer.rb
  app/views/shared/email/_action_of_the_month.html.erb
  app/views/shared/email/_user_climate_actions.html.erb
  app/views/subscription_mailer/one_more_month_email.html.erb
Labels: Project 1

#214 P1/fix/102 eslint config
  .eslintrc.json
  app/assets/main/react_components/.eslintrc.json
  app/assets/main/react_components/common/Button.jsx
  app/assets/main/react_components/common/MonthlyAction.jsx
  app/assets/main/react_components/common/TextBanner.jsx
  app/assets/main/react_components/constants/index.js
  app/assets/main/react_components/contexts/CategoryContext.js
  app/assets/main/react_components/contexts/ClimateActionsContext.js
  app/assets/main/react_components/contexts/DeletedActionContext.js
  app/assets/main/react_components/contexts/FootprintContext.js
  app/assets/main/react_components/contexts/TextContext.js
  app/assets/main/react_components/contexts/UserContext.js
  app/assets/main/react_components/dashboard/Dashboard.jsx
  app/assets/main/react_components/dashboard/climate_actions/ClimateActionsContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCategoryButton.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselHeader.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselList.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/AcceptanceStatistics.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/CategoryColorBanner.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/ImpactPoints.jsx
  app/assets/main/react_components/dashboard/climate_actions/carousel/carousel_card_attributes/NumberOfAccepted.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/ManageUserActions.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/dropdown-kanban/DropDownKanbanContainer.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/AchievementCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/KanbanCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/KanbanCardImage.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/ProgressBar.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/sidebar/Sidebar.jsx
  app/assets/main/react_components/dashboard/footprint/CategoryChart.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintContainer.jsx
  app/assets/main/react_components/dashboard/footprint/FootprintFooter.jsx
  app/assets/main/react_components/dashboard/footprint/MainInfo.jsx
  app/assets/main/react_components/dashboard/footprint/ResultBar.jsx
  app/assets/main/react_components/dashboard/footprint/ResultText.jsx
  app/assets/main/react_components/dashboard/footprint/YourFootprintText.jsx
  app/assets/main/react_components/helpers/AchievementsHelper.js
  app/assets/main/react_components/helpers/DBRequests.js
  app/assets/main/react_components/helpers/ResultHelper.js
  app/assets/main/react_components/helpers/UserActionsHelper.js
Labels: Project 1

#193 Project 2 [fix]: Membership list, web and mobile
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/common/PriceTextV2.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/MembershipAlternativeV2.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipAlternativeV2Desktop.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipAlternativeV2Mobile.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/components/MembershipDropdown.jsx
  config/locales/sign_up/react.de.yml
  config/locales/sign_up/react.en.yml
Labels: Project 2

#216 I did it! text is back
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/card_components/UserActionCardExpanded.jsx
Labels: bug, Project 1

#212 Project 2 [FIX]: Mobile design styling
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/MoneyUsageList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/latest_projects_list/LatestProjectsListV2.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/common/latest_projects_list/components/ProjectSummary.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/ProgressBar.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/common/Title.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/ResultPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/world_section/components/YourFootprintText.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/SignUpPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/form_information_section/components/ArgumentsList.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/MembershipPage.jsx
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/information_section/InformationSection.jsx
  config/locales/sign_up/react.de.yml
  config/locales/sign_up/react.en.yml
  config/locales/sign_up/react.sv.yml
Labels: Project 2

#219 Project 2: Margin fix mobile
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/MembershipsListV2.jsx
Labels: Project 2

#218 Project 2 [fix]: ESLint setup
  .eslintrc.json
  app/assets/main/react_components/.eslintrc.json
Labels: Project 2

#217 Left-aligned text in carousel cards and renaming of maps
  app/assets/main/react_components/dashboard/climate_actions/carousel/CarouselCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/KanbanColumn.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/kanban_card_attributes/AchievementCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/kanban_card_attributes/AchievementCardExpanded.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/kanban_card_attributes/KanbanCardImage.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/kanban_card_attributes/ProgressBar.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/kanban_card_attributes/UserActionCard.jsx
  app/assets/main/react_components/dashboard/climate_actions/manage_actions/kanban/kanban_card_attributes/UserActionCardExpanded.jsx
Labels: Project 1

#222 Centered links below footprint
  app/assets/main/react_components/dashboard/footprint/FootprintFooter.jsx
Labels: Project 1

#220 Project 2 [fix] Copy changes (suggestions)
  config/locales/sign_up/react.en.yml
Labels: Project 2

#221 Project 2: Remove green and add shadow margin V1
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/MembershipAlternative.jsx
Labels: Project 2

#225 Project 2 [fix] Removed react country select
  app/assets/main/react_components/routes/home/CountrySelectContainer.jsx
  app/assets/main/react_components/routes/home/components/CountryForm.jsx
  app/views/home/show.html.erb
Labels: Project 2

#226 Project 2 [fix] Make link smaller
  app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/common/PriceText.jsx
Labels: Project 2

#223 P1/feat/101 move yml files
  app/assets/main/react_components/translations/climate_actions.de.yml
  app/assets/main/react_components/translations/climate_actions.en.yml
  app/assets/main/react_components/translations/climate_actions.sv.yml
  app/views/dashboard/show.html.erb
  config/i18n-tasks.yml
  config/locales/views/climate_actions.de.yml
  config/locales/views/climate_actions.en.yml
  config/locales/views/climate_actions.sv.yml
Labels: Project 1
